version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      zenstack:
        patterns:
          - "@zenstackhq/*"
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "@zenstackhq/*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
