import {
  getDefaultValue,
  getFieldAttributes,
  getFieldTypeName,
  getRelativeSourcePath,
  isFieldRequired,
  stripCommentPrefix,
} from '../extractors';
import {
  type DocMeta as DocumentMeta,
  type GenerationContext,
  type Navigation,
  type RenderOptions,
} from '../types';
import { type DataField } from '@zenstackhq/language/ast';

type SectionMeta = {
  description?: string;
  emoji: string;
};

const SECTION_META: Record<string, SectionMeta> = {
  'Access Policies': {
    description:
      'ZenStack access control rules that determine who can read, create, update, or delete records.',
    emoji: '🔐',
  },
  Fields: {
    description:
      'All fields defined on this entity, including inherited fields from mixins and parent models.',
    emoji: '📋',
  },
  Indexes: {
    description:
      'Database indexes defined on this model for query performance.',
    emoji: '📇',
  },
  Mixins: {
    description: 'Reusable field groups mixed into this model.',
    emoji: '🧩',
  },
  Parameters: {
    description: 'Input parameters accepted by this procedure.',
    emoji: '📥',
  },
  References: { emoji: '📚' },
  Relationships: {
    description: 'Foreign key relationships to other models in the schema.',
    emoji: '🔗',
  },
  Returns: { description: 'The return type of this procedure.', emoji: '📤' },
  'Used By': {
    description: 'Models and fields that reference this type.',
    emoji: '📍',
  },
  'Used in Procedures': {
    description:
      'Procedures that reference this entity as a parameter or return type.',
    emoji: '⚡',
  },
  'Validation Rules': {
    description:
      'Field-level and model-level validation constraints enforced at the ORM layer.',
    emoji: '✅',
  },
  Values: { description: 'Possible values for this enumeration.', emoji: '🏷️' },
};

/**
 * Renders an Index / Category / Entity breadcrumb trail.
 */
export function breadcrumbs(
  entityType: 'Enums' | 'Models' | 'Procedures' | 'Types' | 'Views',
  entityName: string,
  prefix: string,
): string {
  const anchor = entityType.toLowerCase();
  return `[Index](${prefix}index.md) / [${entityType}](${prefix}index.md#${anchor}) / \`${entityName}\``;
}

/**
 * Renders the auto-generated header banner with optional source file and generation date.
 */
export function generatedHeader(
  context?: GenerationContext,
  includeBanner = true,
): string[] {
  if (!includeBanner) {
    return [];
  }

  const metaParts: string[] = [];
  if (context?.schemaFile) {
    metaParts.push(`Source: ${context.schemaFile}`);
  }

  if (context) {
    metaParts.push(`Generated: ${context.generatedAt}`);
  }

  const metaLine = metaParts.length > 0 ? metaParts.join(' · ') : '';

  const contentLines = [
    'DO NOT MODIFY THIS FILE',
    'This file is automatically generated by ZenStack CLI and should not be manually updated.',
  ];
  if (metaLine) {
    contentLines.push(metaLine);
  }

  const maxLength = Math.max(...contentLines.map((l) => l.length));
  const border = '/'.repeat(maxLength + 6);
  const padded = contentLines.map((l) => `// ${l.padEnd(maxLength)} //`);

  return ['```', border, ...padded, border, '```', ''];
}

/**
 * Renders previous/next navigation links at the bottom of entity pages.
 */
export function navigationFooter(nav: Navigation | undefined): string[] {
  if (!nav) {
    return [];
  }

  const parts: string[] = [];
  if (nav.prev) {
    parts.push(`Previous: [${nav.prev.name}](${nav.prev.path})`);
  }

  if (nav.next) {
    parts.push(`Next: [${nav.next.name}](${nav.next.path})`);
  }

  if (parts.length === 0) {
    return [];
  }

  return ['---', '', parts.join(' · '), ''];
}

/**
 * Returns a level-2 heading with an inline anchor, emoji prefix, and optional description for the given section name.
 */
export function sectionHeading(name: string): string[] {
  const meta = SECTION_META[name];
  const emoji = meta?.emoji ?? '';
  const anchor = name.toLowerCase().replaceAll(/\s+/gu, '-');
  const prefix = emoji ? `${emoji} ` : '';
  const lines = [`<a id="${anchor}"></a>`, '', `## ${prefix}${name}`];
  if (meta?.description) {
    lines.push('', `> ${meta.description}`);
  }

  return lines;
}

const ZENSTACK_DOCS_BASE = 'https://zenstack.dev/docs/reference/zmodel';

const ENTITY_DOC_PATHS: Record<string, string> = {
  enum: `${ZENSTACK_DOCS_BASE}/enum`,
  model: `${ZENSTACK_DOCS_BASE}/model`,
  procedure: 'https://zenstack.dev/docs/category/reference',
  type: `${ZENSTACK_DOCS_BASE}/type`,
  view: `${ZENSTACK_DOCS_BASE}/view`,
};

/**
 * Builds a `Map<name, Navigation>` with prev/next links for a sorted list of entity names.
 */
export function buildNavList(
  sortedNames: string[],
  pathPrefix: string,
): Map<string, Navigation> {
  const navMap = new Map<string, Navigation>();
  for (let index = 0; index < sortedNames.length; index++) {
    const current = sortedNames[index]!;
    const nav: Navigation = {};
    if (index > 0) {
      const previous = sortedNames[index - 1]!;
      nav.prev = { name: previous, path: `${pathPrefix}${previous}.md` };
    }

    if (index < sortedNames.length - 1) {
      const next = sortedNames[index + 1]!;
      nav.next = { name: next, path: `${pathPrefix}${next}.md` };
    }

    navMap.set(current, nav);
  }

  return navMap;
}

/**
 * Renders a collapsible `<details>` block containing the raw ZModel declaration and optional source path.
 */
export function declarationBlock(
  cstText: string | undefined,
  sourcePath: string | undefined,
): string[] {
  if (!cstText) {
    return [];
  }

  const stripped = cstText
    .split('\n')
    .filter((line) => !line.trim().startsWith('///'))
    .join('\n');
  const summaryLabel = sourcePath
    ? `Declaration · <code>${sourcePath}</code>`
    : 'Declaration';
  return [
    '<details>',
    `<summary>${summaryLabel}</summary>`,
    '',
    '```prisma',
    stripped,
    '```',
    '',
    '</details>',
    '',
  ];
}

/**
 * Returns fields in declaration or alphabetical order.
 */
export function orderFields(
  fields: DataField[],
  order: RenderOptions['fieldOrder'],
): DataField[] {
  return order === 'alphabetical'
    ? [...fields].sort((a, b) => a.name.localeCompare(b.name))
    : [...fields];
}

/**
 * Renders a "References" section linking to the official ZenStack documentation for the entity type.
 */
export function referencesSection(
  entityType: 'enum' | 'model' | 'procedure' | 'type' | 'view',
): string[] {
  const url = ENTITY_DOC_PATHS[entityType];
  if (!url) {
    return [];
  }

  return [
    '---',
    '',
    ...sectionHeading('References'),
    '',
    `- [ZModel ${entityType}s — ZenStack documentation](${url})`,
    '',
  ];
}

/**
 * Renders a blockquoted description from doc-comments.
 */
export function renderDescription(comments: string[]): string[] {
  const description = stripCommentPrefix(comments);
  if (!description) {
    return [];
  }

  const lines: string[] = [];
  for (const line of description.split('\n')) {
    lines.push(`> ${line}`);
  }

  lines.push('');
  return lines;
}

// ── Shared section renderers ────────────────────────────────────────────

/**
 * Renders category, since, deprecated, table mapping, and source path metadata as a single line.
 */
export function renderMetadata(
  documentMeta: DocumentMeta,
  sourcePath: string | undefined,
  extra?: { dbSchema?: string; mappedTable?: string },
): string[] {
  const parts: string[] = [];
  if (documentMeta.category) {
    parts.push(`**Category:** ${documentMeta.category}`);
  }

  if (documentMeta.since) {
    parts.push(`**Since:** ${documentMeta.since}`);
  }

  if (documentMeta.deprecated) {
    parts.push(`**Deprecated:** ${documentMeta.deprecated}`);
  }

  if (extra?.mappedTable) {
    parts.push(`**Table:** \`${extra.mappedTable}\``);
  }

  if (extra?.dbSchema) {
    parts.push(`**Schema:** \`${extra.dbSchema}\``);
  }

  if (sourcePath) {
    parts.push(`**Defined in:** \`${sourcePath}\``);
  }

  if (parts.length === 0) {
    return [];
  }

  return [parts.join(' · '), ''];
}

/**
 * Renders a 6-column fields table (no Source column). Used by type-page and view-page.
 */
export function renderSimpleFieldsTable(fields: DataField[]): string[] {
  if (fields.length === 0) {
    return [];
  }

  const lines = [
    ...sectionHeading('Fields'),
    '',
    '| Field | Type | Required | Default | Attributes | Description |',
    '| --- | --- | --- | --- | --- | --- |',
  ];
  for (const field of fields) {
    const fieldDescription = stripCommentPrefix(field.comments) || '—';
    const fieldAnchor = `<a id="field-${field.name}"></a>`;
    lines.push(
      `| ${fieldAnchor}\`${field.name}\` | ${getFieldTypeName(field, false)} | ${isFieldRequired(field) ? 'Yes' : 'No'} | ${getDefaultValue(field)} | ${getFieldAttributes(field)} | ${fieldDescription} |`,
    );
  }

  lines.push('');
  return lines;
}

/**
 * Renders "Defined in" line + collapsible declaration block. Used by enum, type, and procedure pages.
 */
export function renderSourceAndDeclaration(
  node: Parameters<typeof getRelativeSourcePath>[0] & {
    $cstNode?: { text?: string };
  },
  schemaDir: string | undefined,
): string[] {
  const sourcePath = getRelativeSourcePath(node, schemaDir);
  const lines: string[] = [];
  if (sourcePath) {
    lines.push(`**Defined in:** \`${sourcePath}\``, '');
  }

  lines.push(...declarationBlock(node.$cstNode?.text, sourcePath));
  return lines;
}
